// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI84wW7u6NC_8-2DtvcAza57dgaQhx044',
    appId: '1:593273181094:web:b341654fdea7fed8f77567',
    messagingSenderId: '593273181094',
    projectId: 'flutterfirbase-54e23',
    authDomain: 'flutterfirbase-54e23.firebaseapp.com',
    storageBucket: 'flutterfirbase-54e23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0SmarcIUBqQpcgjaaCU__EOX9YEG_a0E',
    appId: '1:593273181094:android:cee22db7b5644e08f77567',
    messagingSenderId: '593273181094',
    projectId: 'flutterfirbase-54e23',
    storageBucket: 'flutterfirbase-54e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfBCp3gYPY6nBI19YBYfeSVTVDFWaolRo',
    appId: '1:593273181094:ios:6bf3d4ac69fa60a4f77567',
    messagingSenderId: '593273181094',
    projectId: 'flutterfirbase-54e23',
    storageBucket: 'flutterfirbase-54e23.appspot.com',
    iosClientId: '593273181094-betaab0fcvuhpitv4u8nttlqnip3i1a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.softpati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfBCp3gYPY6nBI19YBYfeSVTVDFWaolRo',
    appId: '1:593273181094:ios:7a338e9012dd87d3f77567',
    messagingSenderId: '593273181094',
    projectId: 'flutterfirbase-54e23',
    storageBucket: 'flutterfirbase-54e23.appspot.com',
    iosClientId: '593273181094-gsbgp0kjmited498vvhtjr60g584kmch.apps.googleusercontent.com',
    iosBundleId: 'com.example.softpati.RunnerTests',
  );
}
